global:
  resolve_timeout: 5m

route:
  receiver: jenkins-rollback-webhook

receivers:
  - name: jenkins-rollback-webhook
    webhook_configs:
      - url: 'http://:8080/generic-webhook-trigger/invoke?token=ROLLBACK_E31CBC_TOKEN'
        http_config:
          basic_auth:
            username: 'admin'
            password: 'APNA_JENKINS_API_TOKEN_YAHAN'
        send_resolved: false
