global:
  resolve_timeout: 5m

route:
  receiver: jenkins-rollback-webhook
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 10m

receivers:
  - name: jenkins-rollback-webhook
    webhook_configs:
      - url: 'http://172.31.34.177:8080/generic-webhook-trigger/invoke?token=ROLLBACK_E31CBC_TOKEN'
        http_config:
          basic_auth:
            username: 'admin'
            password: '11cf511984a3a4e48b247b5ca59152f30b'
        send_resolved: false
