global:
route:
  receiver: 'jenkins-rollback-webhook'
receivers:
- name: 'jenkins-rollback-webhook'
  webhook_configs:
  - url: 'http://172.31.34.177:8080/generic-webhook-trigger/invoke?token=ROLLBACK_E31CBC_TOKEN'
    http_config:
      basic_auth:
        username: 'admin'
        password: '1161fecd3c8bd8d243256278d3515d5f4a'
